# Generated by Django 4.2.2 on 2023-07-09 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='картинка')),
                ('name_city', models.CharField(max_length=50, verbose_name='название города')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('country', models.CharField(max_length=50, verbose_name='город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='картинка')),
                ('name', models.CharField(max_length=50, verbose_name='название отеля')),
                ('country', models.CharField(max_length=50, verbose_name='страна')),
                ('city', models.CharField(max_length=50, verbose_name='город')),
                ('price', models.CharField(max_length=50, verbose_name='цена')),
                ('star', models.FloatField(verbose_name='звезды')),
                ('tourr', models.FloatField(verbose_name='сколько туров')),
            ],
            options={
                'verbose_name': 'Отель',
                'verbose_name_plural': 'Отели',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on', models.CharField(max_length=50, verbose_name='туда')),
                ('out', models.CharField(max_length=50, verbose_name='обратно')),
                ('name', models.CharField(max_length=50, verbose_name='название тура')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours.hotel')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
    ]
