# Generated by Django 4.2.2 on 2023-07-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_rename_advantages_advantage_alter_advantage_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='название отеля')),
                ('country', models.CharField(max_length=50, verbose_name='страна')),
                ('resort', models.CharField(max_length=50, verbose_name='курорт')),
                ('tour_operator', models.CharField(max_length=50, verbose_name='туроператор')),
                ('category', models.FloatField(verbose_name='категория')),
                ('there', models.DateTimeField(verbose_name='туда')),
                ('back', models.DateTimeField(verbose_name='обратно')),
                ('nutrition', models.CharField(max_length=50, verbose_name='питание')),
                ('number', models.CharField(max_length=50, verbose_name='тип номера')),
                ('price', models.FloatField(verbose_name='цена')),
                ('image', models.ImageField(upload_to='', verbose_name='фото отеля')),
            ],
            options={
                'verbose_name': 'Информация об туре',
                'verbose_name_plural': 'Информация об турах',
            },
        ),
    ]
